#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=8gb,walltime=00:30:00
#PBS -N bl.label-timecourse

#SBATCH --ntasks-per-node=1
#SBATCH --mem=8G
#SBATCH --time=00:30:00

set -e
set -x

singularity exec \
  docker://aunnikri642/app-freesurfer-mne-source-recon \
  python3 main.py
